version: "3.7"

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

volumes:
  postgres:
networks:
  app:
    driver: bridge
